deploy:
  branch:
    server: zenci-advanced.backdrop.expert
    username: backdrop
    dir: '{home}/github/{repo_owner}/{repo_name}/{branch}'
    env_vars:
      docroot: '{home}/domains/zenci-advanced.backdrop.expert'
      domain: 'zenci-advanced.backdrop.expert'
      database_name: backdrop_zenci2
      database_user: backdrop_zenci2
      database_pass: DBPASSWORD
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: 'Example advanced site'
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
